### ISSUE TITLE
[Avistaz/Cinemaz] Unexpected response status ServiceUnavailable code from indexer request

### ISSUE THREAD

**Issue by jaum20** [Prowlarr/Indexers#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Avistaz and Cinemaz are not working. Events logs:

```
NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status ServiceUnavailable code from indexer request
   at NzbDrone.Core.Indexers.Definitions.Avistaz.AvistazParserBase.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Avistaz/AvistazParserBase.cs:line 37
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 436
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, SearchCriteriaBase searchCriteria, Boolean isRecent) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 293
```

### Expected Behavior

The indexers should work and not be disabled due to errors

### Steps To Reproduce

1. Add Cinemaz/Avistaz index
2. Wait a few seconds
3. Indexers are disabled due to errors

### Environment

```markdown
- OS: Ubuntu 18
- Prowlarr: 1.5.2.3484
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

[prowlarr.trace.txt](https://github.com/Prowlarr/Indexers/files/11770601/prowlarr.trace.txt)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/prowlarr/) or  [Discord](https://prowlarr.com/discord) for support/questions.

**Comment by bakerboy448** [comment]
> The indexers should work and not be disabled due to errors

the indexer is down and not available as the error indicates. Not a prowlarr issue

**Comment by jaum20** [comment]
it is not down. I can login and download torrents fine

**Comment by ilike2burnthing** [comment]
https://github.com/Jackett/Jackett/issues/13573#issuecomment-1595413383
