### ISSUE TITLE
XXXClub Indexer Issues

### ISSUE THREAD

**Issue by ouenascender** [Prowlarr/Indexers#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Torrent Downloads from XXXClub are not able to download.

GET Requests from torrent/download result in a HTML response not a torrent file. after reviewing the actions of the page I have found that a POST is made to torrents/trending/{infohash} before the get of the torrent file is actioned.

I do not know for to make this change to support the post before the get but i see that actions be done according to the Cardigann spec.

I did make a change to support mag links instead but have now found an issue with searching but I think that is more an issue with how whisparr submits search requests and the XXXclub does not search for no alphanumeric characters

### Expected Behavior

Download Torrent files from XXXclub

### Steps To Reproduce

DL requests either directly using prowlarr search or from Whisparr results in
```
MonoTorrent.TorrentException: Invalid torrent file specified: Invalid torrent file specified
```

### Environment

```markdown
- OS: Fedora 38
- Prowlarr: 1.6.3.3608
- Docker Install: Yes
- Using Reverse Proxy: Tried Both
- Browser: Chromium 113
```

### What branch are you running?

Master

### Trace Logs?

Deleted while testing magnet queries but am unable to reproduce at this time due to issue with non alphanumeric searches

**Comment by ilike2burnthing** [comment]
Went to test this, as it's working fine in Jackett, and found that even searching with the indexer is now failing in Prowlarr with a 417 Expectation Failed status error:

```text
2023-08-17 01:37:08.6|Trace|Http|Req: 29 [GET] /api/v1/search?query=&indexerIds=1&type=search&limit=100&offset=0 (from 127.0.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203)
2023-08-17 01:37:08.6|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-08-17 01:37:08.8|Info|ReleaseSearchService|Searching indexer(s): [XXXClub] for Term: [], Offset: 0, Limit: 100, Categories: []
2023-08-17 01:37:08.8|Trace|Cardigann|Getting Basic search
2023-08-17 01:37:08.8|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-08-17 01:37:08.8|Debug|Cardigann|Populating config vars
2023-08-17 01:37:08.8|Debug|Cardigann|Adding request: https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc
2023-08-17 01:37:08.8|Debug|Cardigann|Downloading Feed https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc
2023-08-17 01:37:08.8|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-08-17 01:37:08.8|Trace|IndexerHttpClient|Req: [GET] https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc
2023-08-17 01:37:08.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-08-17 01:37:08.8|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc: 417.ExpectationFailed (0 bytes) (68 ms)
2023-08-17 01:37:08.8|Warn|Cardigann|HTTP Error - Res: HTTP/2.0 [GET] https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc: 417.ExpectationFailed (0 bytes)
2023-08-17 01:37:08.8|Debug|Cardigann|Parsing
2023-08-17 01:37:08.8|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-08-17 01:37:08.8|Trace|Cardigann|Unexpected Response content (0 bytes): 
2023-08-17 01:37:08.8|Trace|EventAggregator|Publishing ProviderStatusChangedEvent<IIndexer>
2023-08-17 01:37:08.8|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> -> IndexerStatusController
2023-08-17 01:37:08.8|Trace|EventAggregator|ProviderStatusChangedEvent<IIndexer> <- IndexerStatusController
2023-08-17 01:37:08.8|Trace|Http|Req: 30 [GET] /api/v1/indexerStatus (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203)
2023-08-17 01:37:08.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-08-17 01:37:08.9|Trace|ConfigService|Using default config value for 'uilanguage' defaultValue:'en'
2023-08-17 01:37:08.9|Trace|EventAggregator|Publishing HealthCheckFailedEvent
2023-08-17 01:37:08.9|Trace|Http|Res: 30 [GET] /api/v1/indexerStatus: 200.OK (4 ms)
2023-08-17 01:37:08.9|Debug|Api|[GET] /api/v1/indexerStatus: 200.OK (4 ms)
2023-08-17 01:37:08.9|Trace|EventAggregator|HealthCheckFailedEvent -> NotificationService
2023-08-17 01:37:08.9|Trace|EventAggregator|HealthCheckFailedEvent <- NotificationService
2023-08-17 01:37:08.9|Trace|EventAggregator|Publishing HealthCheckCompleteEvent
2023-08-17 01:37:08.9|Trace|EventAggregator|HealthCheckCompleteEvent -> HealthController
2023-08-17 01:37:08.9|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2023-08-17 01:37:08.9|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2023-08-17 01:37:08.9|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2023-08-17 01:37:08.9|Trace|Http|Req: 31 [GET] /api/v1/health (from ::1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203)
2023-08-17 01:37:08.9|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-08-17 01:37:08.9|Trace|Http|Res: 31 [GET] /api/v1/health: 200.OK (4 ms)
2023-08-17 01:37:08.9|Debug|Api|[GET] /api/v1/health: 200.OK (4 ms)
2023-08-17 01:37:08.8|Warn|Cardigann|https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc

[v1.7.4.3769] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status ExpectationFailed code from indexer request
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 58
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 425
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, SearchCriteriaBase searchCriteria, Boolean isRecent) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 294
RequestUri: https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc;StatusCode: ExpectationFailed;ContentLength: 0

2023-08-17 01:37:09.0|Trace|EventAggregator|Publishing IndexerQueryEvent
2023-08-17 01:37:09.0|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2023-08-17 01:37:09.0|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2023-08-17 01:37:09.0|Debug|ReleaseSearchService|Total of 0 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [] from 1 indexer(s)
2023-08-17 01:37:09.0|Trace|Http|Res: 29 [GET] /api/v1/search?query=&indexerIds=1&type=search&limit=100&offset=0: 200.OK (415 ms)
2023-08-17 01:37:09.0|Debug|Api|[GET] /api/v1/search?query=&indexerIds=1&type=search&limit=100&offset=0: 200.OK (415 ms)
```

Oddly I found that adding the current, unaltered UA header to the definition resolves the issue (downloads as well):

```yml
  headers:
    User-Agent: ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203"]
```

```text
2023-08-17 01:36:30.1|Trace|Http|Req: 28 [GET] /api/v1/search?query=&indexerIds=2&type=search&limit=100&offset=0 (from 127.0.0.1 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203)
2023-08-17 01:36:30.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-08-17 01:36:30.3|Info|ReleaseSearchService|Searching indexer(s): [XXXClub2] for Term: [], Offset: 0, Limit: 100, Categories: []
2023-08-17 01:36:30.3|Trace|Cardigann|Getting Basic search
2023-08-17 01:36:30.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-08-17 01:36:30.3|Debug|Cardigann|Populating config vars
2023-08-17 01:36:30.3|Debug|Cardigann|Adding request: https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc
2023-08-17 01:36:30.3|Debug|Cardigann|Downloading Feed https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc
2023-08-17 01:36:30.3|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-08-17 01:36:30.3|Trace|IndexerHttpClient|Req: [GET] https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc
2023-08-17 01:36:30.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-08-17 01:36:30.8|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://xxxclub.to/torrents/browse/all/?sort=uploaded&order=desc: 200.OK (32198 bytes) (399 ms)
2023-08-17 01:36:30.8|Debug|Cardigann|Parsing
2023-08-17 01:36:30.8|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-08-17 01:36:30.8|Debug|Cardigann|Got 25 releases
2023-08-17 01:36:30.8|Trace|EventAggregator|Publishing IndexerQueryEvent
2023-08-17 01:36:30.8|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2023-08-17 01:36:30.8|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2023-08-17 01:36:30.8|Debug|ReleaseSearchService|Total of 25 reports were found for Term: [], Offset: 0, Limit: 100, Categories: [] from 1 indexer(s)
2023-08-17 01:36:30.8|Trace|Http|Res: 28 [GET] /api/v1/search?query=&indexerIds=2&type=search&limit=100&offset=0: 200.OK (750 ms)
2023-08-17 01:36:30.8|Debug|Api|[GET] /api/v1/search?query=&indexerIds=2&type=search&limit=100&offset=0: 200.OK (750 ms)
```

Wider issue?

**Comment by Qstick** [comment]
> Wider Issue?

Yea, we ran into it with a couple others, we don't mask the UA in Prowlarr, but believe Jackett does by default in web client.
