### ISSUE TITLE
Classix Unlimited - "Download selectors didn't match"

### ISSUE THREAD

**Issue by albino1** [Prowlarr/Indexers#361]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Attempting to download from Classix Unlimited via Prowlarr errors with "Download selectors didn't match".  No other trackers have this issue for me.

### Expected Behavior

When you click download it will download.

### Steps To Reproduce

Search for something with Classix Unlimited enabled, then click the Save button.

### Environment

```markdown
- OS: Rocky Linux 8.8
- Prowlarr: 1.7.4.3769
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Firefox + Chrome
```

### What branch are you running?

Master

### Trace Logs?

Example 1:

```
2023-09-01 03:35:24.2|Info|ReleaseSearchService|Searching indexer(s): [Classix Unlimited] for Term: [removed], Offset: 0, Limit: 0, Categories: []
2023-09-01 03:35:41.0|Error|NewznabController|NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1

[v1.7.4.3769] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 961
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.GetDownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 203
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 193
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 189
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 294
```

Example 2:

```
2023-09-01 04:22:24.2|Info|ReleaseSearchService|Searching indexer(s): [Classix Unlimited] for Term: [removed], Offset: 0, Limit: 0, Categories: []
2023-09-01 04:22:37.1|Error|NewznabController|NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1

[v1.7.4.3769] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 961
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.GetDownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 203
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 193
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 189
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 294
```

Example 3:

```
023-09-01 04:38:36.5|Error|NewznabController|NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1

[v1.7.4.3769] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 961
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.GetDownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 203
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 193
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 189
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 294
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by ilike2burnthing** [comment]
Provide trace logs so we can see what is actually being returned.

**Comment by albino1** [comment]
I went ahead and installed a fresh version of Prowlarr Nightly v1.8.5.3894 using [the linuxserver.io docker image](https://hub.docker.com/r/linuxserver/prowlarr) so I could get clean logs.  This is a different environment, with a different version of Prowlarr, but it exhibits the same error:

```
2023-09-01 19:28:06.1|Trace|IndexerHttpClient|Res: HTTP/1.1 [GET] http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1: 200.OK (29033 bytes) (513 ms)
2023-09-01 19:28:06.1|Debug|Cardigann|CardigannIndexer (classix): Selector a[href^="download.php?id="] could not match any elements.
2023-09-01 19:28:06.1|Error|NewznabController|NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1

[v1.8.5.3894] NzbDrone.Core.Indexers.Definitions.Cardigann.Exceptions.CardigannException: Download selectors didn't match for http://classix-unlimited.co.uk/download.php?id=(removed)&hit=1
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannRequestGenerator.DownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannRequestGenerator.cs:line 966
   at NzbDrone.Core.Indexers.Definitions.Cardigann.Cardigann.GetDownloadRequest(Uri link) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/Cardigann.cs:line 198
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 194
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 162
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 255
```

[prowlarr.trace.txt](https://github.com/Prowlarr/Indexers/files/12501058/prowlarr.trace.txt)

**Comment by ilike2burnthing** [comment]
Looking at the indexer, it's expecting there to be no download link on the results page, but rather it's on a separate download page. From the HTML in your log however, there's a direct torrent URL available on the search results page.

While the download page is still accessed, the selector isn't finding a match, and the HTML for it isn't returned in the trace log. You could fire up a Jackett container, add the indexer, enable enhanced logging, and try downloading to see the returned HTML, but that may not be necessary here.

While it should be a simple enough fix, none of the maintainers here or over at Jackett have an account for the tracker to test, so I'd need you to check that there isn't an account setting that you've enabled/disabled/changed which shows/hides a download button, or a change in layout/style/design/skin/whatever which would achieve the same.

Also, are size, seeders, and leechers being picked up correctly in Prowlarr? As far as I can tell from the HTML, they shouldn't be. In fact the more I look, the more I see needs updated (if you haven't made some change to the site layout in your account settings). If you're up for sending an invite, let me know, as that would be a lot easier for both of us.

**Comment by albino1** [comment]
This tracker is extremely bare bones with limited functionality and there are barely any settings you can change at all, none of which would affect things like download links or results.

There is indeed a download button on the search results page, and then on the torrent details page there is another download button plus a download text link.  All three of the download links are identical, something along the lines of:

http://classix-unlimited.co.uk/download.php?id=123456&name=Title.torrent

I'm unclear why the selector doesn't match.  If I take the regex from [the classix yaml](https://github.com/Prowlarr/Indexers/blob/44dc9197cdaf61e79da102f4e73ebfffdd4ea2ec/definitions/v7/classix.yml#L4) and paste it into Inspector it immediately picks the correct link:

![classix](https://github.com/Prowlarr/Indexers/assets/12164957/b405413a-e4ad-45cd-873f-3daa6f702dd2)

It appears to be reporting sizes and peers correctly in Prowlarr:

![classix2](https://github.com/Prowlarr/Indexers/assets/12164957/dc9421ae-9fc0-4a09-9821-90b5303b8032)

Installing the linuxserver.io Jackett docker, trying to download, and then looking at the log, I get a result returned correctly, followed by the same download selectors problem, followed by a bunch of crazy characters.  Unlike prowlarr there's no easy way to save the log.txt file so far as I can tell, but I took a screenshot of the crazy characters and I just selected the whole page and dropped it into a txt file in case there's something worth looking at even though it will be hard to read:

<details>
  <summary>Classix Jackett Log Screenhot</summary>

![classix3](https://github.com/Prowlarr/Indexers/assets/12164957/d6f0c2b6-99f9-443e-85fd-96ba85237834)

</details>

[jackett enhanced log.txt](https://github.com/Prowlarr/Indexers/files/12504332/jackett.enhanced.log.txt)

Unfortunately, I can't send you an invite, but Classix is really easy to join and many trackers have invite threads or threads where people will just give you one if you ask with almost no requirements.

**Comment by ilike2burnthing** [comment]
Yea, that's' the torrent file, so seemingly while there's a details page there's no download page anymore.

Can you provide an HTML dump of the torrents-search.php page?

Can you also confirm whether you can search by multiple categories at the same time? The current indexer is using:

> http://classix-unlimited.co.uk/torrents-search.php?filter_cat[1]=1&filter_cat[2]=1&filter_cat[3]=1&search="2023"&incldead=0

I'm assuming quotes are required around search keywords so that the site doesn't perform partial matches?

**Comment by albino1** [comment]
Right, quotes are required because the search is terrible and it matches any keyword unless it's quoted.

Here's the torrents-search.php with the same result on it that I used in my example above:

[torrents-search.txt](https://github.com/Prowlarr/Indexers/files/12504729/torrents-search.txt)

Categories don't appear to work as intended.  The best results are just not selecting any categories as the results returned aren't properly reflecting the categories selected anyway.  For example, here is your example search:

<details>
  <summary>Default with no categories selected</summary>

![csx-results1](https://github.com/Prowlarr/Indexers/assets/12164957/fbdf59af-e92e-4bf5-9ba9-9b9e472081b8)

</details>

http://classix-unlimited.co.uk/torrents-search.php?filter_cat%5B1%5D=1&filter_cat%5B2%5D=1&filter_cat%5B3%5D=1&search=%222023%22&incldead=0


And here it is limited to `TV - Series: DVD` by checking the checkbox, which is the same and doesn't work:

<details>
  <summary>TV - Series: DVD Checkbox Checked but dropdown still set to All Types</summary>

![csx-results2](https://github.com/Prowlarr/Indexers/assets/12164957/6bdcf240-d91a-4abf-b5c4-f5e80a95817b)

</details>

http://classix-unlimited.co.uk/torrents-search.php?c5=1&search=%222023%22&cat=0&incldead=0&freeleech=0&lang=0

And then here it is limiting it by changing the search dropdown to `TV - Series: DVD` which then seems to work, but doesn't allow you to select multiple categories:

<details>
  <summary>Search dropdown changed to TV - Series: DVD which also auto-checks the checkbox</summary>

![csx-results3](https://github.com/Prowlarr/Indexers/assets/12164957/5457eb3a-0241-4eb2-90d4-d62cc7953394)

</details>

http://classix-unlimited.co.uk/torrents-search.php?c5=1&search=%222023%22&cat=5&incldead=0&freeleech=0&lang=0

**Comment by ilike2burnthing** [comment]
Ah, the layout is slightly different for the latest torrents listed on index.php, makes more sense now.

Thanks for your help, just the last few things and then we should be good to go.

1) Does the following work for selecting multiple categories?

> http://classix-unlimited.co.uk/torrents-search.php?c1=1&c2=1&c3=1&search=&incldead=0

That should return only `Movies: DVD-Untouched`, `Movies: Divx/Xvid/Avi`, and `Movies: SVCD/VCD` results. If not, tick several category boxes and click search, then post the URL.

2) Are the categories `Media: pdf`, `Other: Educational/Instructional`, and `Other: Related Material` eBooks, magazines/newspapers, textbooks, etc.? If so, which are which?

3) Does searching for `"1987 Crazy Love"` return no results? If so, does either `"1987" "Crazy" "Love"` or `+1987 +Crazy +Love` return the **one** correct result?

4) Can you provide an HTML dump of the torrents-search.php page with it including a freeleech result?

5) Are there minimum seed time and/or minimum ratio requirements for torrents, or your account generally, to avoid hit and run or low ratio warnings? If so, please detail these. If you're unsure, they can usually be found in the rules, FAQ or a HnR/requirements/snatches page.

**Comment by albino1** [comment]
> 1. Does the following work for selecting multiple categories?

To me it looks like this does not work as intended as there's results from other categories (like `TV: Series: DVD`) even though the ones you selected are checked:

<details>
  <summary>Screenshot of example URL</summary>

![classix4](https://github.com/Prowlarr/Indexers/assets/12164957/8166abed-3c19-4db5-b807-ef3e31cc2167)

</details>
 
> 2. Are the categories `Media: pdf`, `Other: Educational/Instructional`, and `Other: Related Material` eBooks, magazines/newspapers, textbooks, etc.? If so, which are which?

`Media: pdf`: 67
`Other: Education/Instructional`: 63
`Other: Related Material`: 61

> 3. Does searching for `"1987 Crazy Love"` return no results? If so, does either `"1987" "Crazy" "Love"` or `+1987 +Crazy +Love` return the **one** correct result?

`"Crazy Love 1987"`: correct result
`"1987 Crazy Love"`: correct result
`"1987" "Crazy" "Love"`: fails, it's the same as `1987 Crazy Love` with no quotes at all
`+1987 +Crazy +Love`: correct result, though for some reason I thought this didn't work previously like a year ago, but seems to now, so maybe that's the best option.


> 4. Can you provide an HTML dump of the torrents-search.php page with it including a freeleech result?

I would have said there is no freeleech results because the whole site is pretty much freeleech, but turns out you get different results if you do that so maybe it is a thing :)

[classix-freeleech.txt](https://github.com/Prowlarr/Indexers/files/12504937/classix-freeleech.txt)

> 5. Are there minimum seed time and/or minimum ratio requirements for torrents, or your account generally, to avoid hit and run or low ratio warnings? If so, please detail these. If you're unsure, they can usually be found in the rules, FAQ or a HnR/requirements/snatches page.

There are no ratio requirements, however there is a minimum 48 hour seed time.  Here's the relevant portion from their rules page:


> - Access to the newest torrents is conditional on your participation in our community. We do not impose absolute ratios, as we would rather promote an environment where people participate gladly. However, this can change if this policy is abused.
> - Please seed all torrents to a 1:1 ratio wherever possible or seed a minimum of 48 hours. This 48 hour period can be spread over a 7 day period. These are only minimum requirements and we strongly encourage you to seed for as long as possible. Remember, a dead torrent is of no use to anyone.
> - Failure to seed the required period will result as a Hit ‘n Run. The site has the capability to monitor this compliance through the ‘Snatchlist’ button that is located on the torrent description page.
> - Infractions for Hit ‘n Run will result in the member’s account being suspended. First infraction will be for 7 days, second infraction will be for 15 days, each infraction after will be for 30 days. If it becomes habitual then the member may be banned unless the member can present sufficient justification as to the cause of why it is taking place.

**Comment by albino1** [comment]
> Sorry, I think I was unclear with question 2; I have all the cat IDs, I just need to know if the torrents for those specific categories are eBooks, magazines/newspapers, textbooks, etc., and if so then which are which.

Apologies, I see now.

`Media: pdf`: This is literally only one file, and appears to be a scan of a book.
`Other: Education/Instructional`: This appears to be everything from exercise videos, to comedy, to language learning videos, with maybe some ebooks tossed in.
`Other: Related Material`: This is more ebooks and PDFs of books.

> Are those 'freeleech' torrents marked as freeleech in some way, even on their details pages? I can't see anything in the HTML of the results page, which means Jackett/Prowlarr can't identify them as such.

There's nothing on the page that denotes them as freeleech, however I think what's happening is that all torrents uploaded by the user and admin `grumpyman57` are considered freeleech.

> Extract to the [custom folder](https://wiki.servarr.com/prowlarr/indexers#adding-a-custom-yml-definition) and try this test indexer - [classix-test.zip](https://github.com/Prowlarr/Indexers/files/12504967/classix-test.zip).
> 
> Results' categories, dates, and downloads should all work. Sort and order settings have also been added, as have genre and description.

Success!

```
2023-09-03 03:34:54.4|Info|ReleaseSearchService|Searching indexer(s): [Classix-Test] for Term: [crazy love 1987], Offset: 0, Limit: 100, Categories: []
2023-09-03 03:34:54.4|Trace|Cardigann|Getting Basic search
2023-09-03 03:34:54.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-09-03 03:34:54.4|Debug|Cardigann|Populating config vars
2023-09-03 03:34:54.4|Debug|Cardigann|Adding request: http://classix-unlimited.co.uk/torrents-search.php?search=%2Bcrazy+%2Blove+%2B1987&cat=0&incldead=0&freeleech=0&lang=0&sort=id&order=desc
2023-09-03 03:34:54.4|Debug|Cardigann|Downloading Feed http://classix-unlimited.co.uk/torrents-search.php?search=%2Bcrazy+%2Blove+%2B1987&cat=0&incldead=0&freeleech=0&lang=0&sort=id&order=desc
2023-09-03 03:34:54.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-09-03 03:34:54.4|Trace|IndexerHttpClient|Req: [GET] http://classix-unlimited.co.uk/torrents-search.php?search=%2Bcrazy+%2Blove+%2B1987&cat=0&incldead=0&freeleech=0&lang=0&sort=id&order=desc
2023-09-03 03:34:54.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-03 03:34:55.3|Trace|IndexerHttpClient|Res: HTTP/1.1 [GET] http://classix-unlimited.co.uk/torrents-search.php?search=%2Bcrazy+%2Blove+%2B1987&cat=0&incldead=0&freeleech=0&lang=0&sort=id&order=desc: 200.OK (38561 bytes) (958 ms)
2023-09-03 03:34:55.4|Debug|Cardigann|Parsing
2023-09-03 03:34:55.4|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-09-03 03:34:55.4|Debug|Cardigann|classix-test: Error while parsing DateTime "09-15-2015", using layout "dd-MM-yyyy" (dd-MM-yyyy): The DateTime represented by the string '09-15-2015' is not supported in calendar 'System.Globalization.GregorianCalendar'.
2023-09-03 03:34:55.5|Debug|Cardigann|Got 1 releases
2023-09-03 03:34:55.5|Trace|EventAggregator|Publishing IndexerQueryEvent
2023-09-03 03:34:55.5|Trace|EventAggregator|IndexerQueryEvent -> HistoryService
2023-09-03 03:34:55.5|Trace|EventAggregator|IndexerQueryEvent <- HistoryService
2023-09-03 03:34:55.5|Debug|ReleaseSearchService|Total of 1 reports were found for Term: [crazy love 1987], Offset: 0, Limit: 100, Categories: [] from 1 indexer(s)
2023-09-03 03:34:55.5|Trace|Http|Res: 63353 [GET] /api/v1/search?query=crazy%20love%201987&indexerIds=11&type=search&limit=100&offset=0: 200.OK (1221 ms)
2023-09-03 03:34:55.5|Debug|Api|[GET] /api/v1/search?query=crazy%20love%201987&indexerIds=11&type=search&limit=100&offset=0: 200.OK (1221 ms)
2023-09-03 03:34:57.8|Trace|Http|Req: 63354 [GET] /11/download?apikey=(removed)&link=removed&file=Crazy+Love+(1987)+DVD9+NTSC (from 47.*.*.244 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0)
2023-09-03 03:34:57.8|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-03 03:34:57.8|Trace|DownloadService|Attempting download of http://classix-unlimited.co.uk/download.php?id=(removed)&name=Crazy Love %281987%29.torrent
2023-09-03 03:34:57.8|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2023-09-03 03:34:57.8|Debug|Cardigann|Populating config vars
2023-09-03 03:34:57.8|Trace|RateLimitService|Rate Limit triggered, delaying 'classix-unlimited.co.uk' for 1.998 sec
2023-09-03 03:34:59.5|Trace|Scheduler|Pending Tasks: 0
2023-09-03 03:34:59.8|Trace|IndexerHttpClient|Req: [GET] http://classix-unlimited.co.uk/download.php?id=(removed)&name=Crazy%20Love%20%281987%29.torrent
2023-09-03 03:34:59.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2023-09-03 03:35:00.2|Trace|IndexerHttpClient|Res: HTTP/1.1 [GET] http://classix-unlimited.co.uk/download.php?id=(removed)&name=Crazy%20Love%20%281987%29.torrent: 200.OK (29033 bytes) (388 ms)
2023-09-03 03:35:00.2|Debug|Cardigann|Downloaded for release finished (29033 bytes from http://classix-unlimited.co.uk/download.php?id=(removed)&name=Crazy%20Love%20%281987%29.torrent)
2023-09-03 03:35:00.2|Trace|DownloadService|Downloaded 29033 bytes from http://classix-unlimited.co.uk/download.php?id=(removed)&name=Crazy Love %281987%29.torrent
2023-09-03 03:35:00.2|Trace|EventAggregator|Publishing IndexerDownloadEvent
2023-09-03 03:35:00.2|Trace|EventAggregator|IndexerDownloadEvent -> NotificationService
2023-09-03 03:35:00.2|Trace|EventAggregator|IndexerDownloadEvent <- NotificationService
2023-09-03 03:35:00.2|Trace|EventAggregator|IndexerDownloadEvent -> HistoryService
2023-09-03 03:35:00.2|Trace|EventAggregator|IndexerDownloadEvent <- HistoryService
2023-09-03 03:35:00.2|Trace|Http|Res: 63354 [GET] /11/download?apikey=(removed)&link=removed&file=Crazy+Love+(1987)+DVD9+NTSC: 200.OK (2397 ms)
2023-09-03 03:35:05.1|Trace|Http|Req: 63355 [GET] /api/v1/health (from 47.*.*.244 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0)
2023-09-03 03:35:05.1|Trace|Http|Req: 63356 [GET] /api/v1/system/status (from 47.*.*.244 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0)
2023-09-03 03:35:05.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-03 03:35:05.1|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-03 03:35:05.1|Trace|Http|Res: 63355 [GET] /api/v1/health: 200.OK (0 ms)
2023-09-03 03:35:05.1|Debug|Api|[GET] /api/v1/health: 200.OK (0 ms)
2023-09-03 03:35:05.1|Trace|Http|Res: 63356 [GET] /api/v1/system/status: 200.OK (1 ms)
2023-09-03 03:35:05.1|Debug|Api|[GET] /api/v1/system/status: 200.OK (1 ms)
2023-09-03 03:35:06.0|Trace|Http|Req: 63357 [GET] /api/v1/log/file (from 47.*.*.244 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0)
2023-09-03 03:35:06.0|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-09-03 03:35:06.0|Trace|Http|Res: 63357 [GET] /api/v1/log/file: 200.OK (1 ms)
2023-09-03 03:35:06.0|Debug|Api|[GET] /api/v1/log/file: 200.OK (1 ms)
2023-09-03 03:35:08.8|Trace|Http|Req: 63358 [GET] /logfile/prowlarr.trace.txt (from 47.*.*.244 Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0)
```

**Comment by ilike2burnthing** [comment]
Fix will be available with the next definitions update. Thanks for your help.

**Comment by albino1** [comment]
Sounds good.  Thank you for walking me through the process, and glad I could be of service!
