### ISSUE TITLE
Knaben Indexer fails to exctract the magnet url for certain entries

### ISSUE THREAD

**Issue by sdaqo** [Prowlarr/Indexers#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some entries of the knaben indexer fail because the magnet url that the yaml definition is grabbing is not always a magnet url. Sometimes, especially for entries that were cached a while ago, the link is a normal http url that redirects to the magnet link, for example, [this](https://knaben.eu/search/tokyo-ga%20[1985,%20,%20bdremux%201080i]%20vo%20+%20sub%20rus,%20eng+%20original%20eng/0/1/seeders) torrent points to this link: https://knaben.eu/live/dl/rutracker/?path=Q2ZESjhMU1h6NDVqajc1Q2tvcjZpb3AzVE5qcDRTaV9ISmJRZnlONk9ldE13blQyV3g2aWtUaGpQaUlaODdBRjlEdHNXQWRkOHpWczZSWFFCdjFEQnc2TkZuTGJkVzNFNkhyODFxRmFkM3pzWXlMdWpmSHpuNFRVTXd2Q0s2V01NYnRyVHVSMlYxQmJrRHhMc1dzWmszTGh0SEtfTktxUGZJQXNXd3RJOENQX1FFNGI&file=Tokyo-Ga+%5B1985%2C+%2C+BDRemux+1080i%5D+VO+%2B+Sub+Rus%2C+Eng%2B+Original+Eng&knabensource=https%3A%2F%2Frutracker.org%2Fforum%2Fviewtopic.php%3Ft%3D4854014 which in turn points to the magnet url for that particular entry.

### Expected Behavior

yaml definition should only grab the magnet link if it is really a magnet url and if not it should grab the magnet url that the http url points to.****

### Steps To Reproduce

1. Grab a torrent of knaben that does not directly point to a magnet url (e.g. [this](https://knaben.eu/search/tokyo-ga%20[1985,%20,%20bdremux%201080i]%20vo%20+%20sub%20rus,%20eng+%20original%20eng/0/1/seeders))
2. Knaben indexer fails with `System.NotSupportedException: The 'magnet' scheme is not supported.: The 'magnet' scheme is not supported.`

### Environment

```markdown
- OS: Truenas Scale
- Prowlarr: Prowlarr 1.12.0.4188
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

```
2024-01-13 12:58:32.0|Info|ReleaseSearchService|Searching indexer(s): [Knaben] for Term: [Tokyo-Ga [1985, , BDRemux 1080i] VO + Sub Rus, Eng+ Original Eng], Offset: 0, Limit: 100, Categories: []
2024-01-13 12:58:44.0|Error|Cardigann|Download failed
2024-01-13 12:58:44.0|Error|NewznabController|System.NotSupportedException: The 'magnet' scheme is not supported.

[v1.12.0.4188] System.NotSupportedException: The 'magnet' scheme is not supported.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 112
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 103
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.Download(Uri link) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 211
   at NzbDrone.Core.Download.DownloadService.DownloadReport(String link, Int32 indexerId, String source, String host, String title) in ./Prowlarr.Core/Download/DownloadService.cs:line 162
   at NzbDrone.Api.V1.Indexers.NewznabController.GetDownload(Int32 id, String link, String file) in ./Prowlarr.Api.V1/Indexers/NewznabController.cs:line 269


2024-01-13 13:00:31.2|Error|QBittorrent|Failed to parse magnetlink for release 'Tokyo-Ga [1985, , BDRemux 1080i] VO + Sub Rus, Eng+ Original Eng': 'https://knaben.eu/live/dl/rutracker/?path=Q2ZESjhMU1h6NDVqajc1Q2tvcjZpb3AzVE5qcDRTaV9ISmJRZnlONk9ldE13blQyV3g2aWtUaGpQaUlaODdBRjlEdHNXQWRkOHpWczZSWFFCdjFEQnc2TkZuTGJkVzNFNkhyODFxRmFkM3pzWXlMdWpmSHpuNFRVTXd2Q0s2V01NYnRyVHVSMlYxQmJrRHhMc1dzWmszTGh0SEtfTktxUGZJQXNXd3RJOENQX1FFNGI&file=Tokyo-Ga+%5B1985%2C+%2C+BDRemux+1080i%5D+VO+%2B+Sub+Rus%2C+Eng%2B+Original+Eng&knabensource=https%3A%2F%2Frutracker.org%2Fforum%2Fviewtopic.php%3Ft%3D4854014'

[v1.12.0.4188] System.FormatException: Magnet links must start with 'magnet:'.
   at MonoTorrent.MagnetLink.FromUri(Uri uri)
   at MonoTorrent.MagnetLink.Parse(String uri)
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(TorrentInfo release, String magnetUrl) in ./Prowlarr.Core/Download/TorrentClientBase.cs:line 170```

**Comment by sdaqo** [comment]
Thanks for the quick fix! And yes I will keep that in mind for the future.
