### ISSUE TITLE
TurkTorrent.us not working

### ISSUE THREAD

**Issue by ghost** [Prowlarr/Indexers#411]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm trying to add the TurkTorrent.us private tracker but it fails.
I've followed the instructions and torrent listing is set to "classic" and the language to "english".
I've copied the full cookie request header btw.
```tsue_guest_language=1; shoutboxChannelID=1; tsue_member=xxx```

The logfile returns:
```
2024-02-28 20:27:58.5|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
```

### Expected Behavior

Working TurkTorrent.us indexer

### Environment

```markdown
- OS: Fedora 39 using Podman
- Prowlarr: 1.13.3.4273-ls54 by linuxserver.io
- Docker Install: yes, using podman
- Using Reverse Proxy: no
- Browser: Firefox 123.0
```

### What branch are you running?

Master

### Trace Logs?
```
2024-02-28 21:07:24.9|Warn|Cardigann|Unable to connect to indexer

[v1.13.3.4273] System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.AddRequestHeaders(HttpRequestMessage webRequest, HttpHeader headers) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 210
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Prowlarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Prowlarr.Common/Http/HttpClient.cs:line 171
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 42
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 573
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 757


2024-02-28 21:07:25.0|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. The format of value '' is invalid.
2024-02-28 21:12:31.0|Warn|ProwlarrErrorPipeline|Invalid request Validation failed: 
 -- : Query successful, but no results were returned from your indexer. This may be an issue with the indexer, your indexer category settings, or other indexer settings such as search freeleech only etc.
```
### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by sametakofficial** [comment]
> can you send me the script too
> 
> > > > Nevermind I got it to work :) It seems I had to properly decode the `%3D%3D` part to `==` of the `tsue_member` value. Furthermore I need to leave out the other two values `tsue_guest_language=1` and `shoutboxChannelID=1`.
> > > 
> > > 
> > > I changed %3D%3D to == but haven't fixed it for me.
> > 
> > 
> > it could e because turktorrent.us now protected with cloudflare challange page, if you need help to solve it, ı can give you a script that ı made

rss gelmiş gözümüz aydın yeni fark ettim :D
