### ISSUE TITLE
"The Old School" don't work anymore

### ISSUE THREAD

**Issue by screamjojo** [Prowlarr/Indexers#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please can you update french private tracker theoldschool.cc, since yesterday the site has been change and the indexer don't work anymore.

### Expected Behavior

Please can you update french private tracker theoldschool.cc

### Environment

```markdown
- OS: Synology DSM 7
- Prowlarr: 1.18.0.4543
- Docker Install:Yes
- Using Reverse Proxy: no
- Browser:
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

[v1.18.0.4543] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [GET] at [https://theoldschool.cc/api/torrents/filter?categories[]=2&categories[]=7&categories[]=8&categories[]=9&categories[]=10&sortField=created_at&sortDirection=desc&perPage=100]
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 700
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 604
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, SearchCriteriaBase searchCriteria, Boolean isRecent) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 422

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by screamjojo** [comment]
I don't think because jacket make a commit : https://github.com/Jackett/Jackett/commit/b1ca9060afb016e6d2030b24caef6fa04bdc5fbb
https://github.com/Jackett/Jackett/issues/13691
