### ISSUE TITLE
Unable to connect to indexer (Yggttorent) 

### ISSUE THREAD

**Issue by CorentinWicht** [Prowlarr/Indexers#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Yesterday I realized that prowlarr couldn't connect to Yggtorrent/Yggcookie anymore, though I did not change my settings and I am fully up-to-date (_see below_).

Here is the error returned by Prowlarr (with and without Flaresolverr):
![image](https://github.com/user-attachments/assets/ead0dab2-736a-4ea9-89de-50f897645193)

Best,

C.

### Expected Behavior

Connection should be established since my credentials are working when I reach Yggtorrent website directly.

Yggtorrent server is online:
![image](https://github.com/user-attachments/assets/899801d1-e7b5-4682-b78e-435f232a12c7)

### Environment

```markdown
- OS: Ubuntu 24.04
- Prowlarr: 1.20.1.4603-ls78
- Flaresolverr: 3.3.21
- Docker Install: Yes (through Portainer)
- Using Reverse Proxy: Linuxserver/swag
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

**Prowlarr**

```
2024-07-16T06:12:47.441476529Z [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
2024-07-16T06:12:47.441508536Z  -- : Unable to connect to indexer, check the log above the ValidationFailure for more details. HTTP request failed: [403:Forbidden] [GET] at [https://www.ygg.re/auth/login] 
2024-07-16T06:13:20.700102225Z [Info] ReleaseSearchService: Searching indexer(s): [Il Corsaro Nero] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070] 
2024-07-16T06:13:20.700325721Z [Info] ReleaseSearchService: Searching indexer(s): [Torrent9] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000] 
2024-07-16T06:13:20.700672628Z [Info] ReleaseSearchService: Searching indexer(s): [TheRARBG] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070] 
2024-07-16T06:13:20.701033968Z [Info] ReleaseSearchService: Searching indexer(s): [GkTorrent] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5070] 
2024-07-16T06:13:20.701291663Z [Info] ReleaseSearchService: Searching indexer(s): [OxTorrent] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000] 
2024-07-16T06:13:20.701612211Z [Info] ReleaseSearchService: Searching indexer(s): [Internet Archive] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000] 
2024-07-16T06:13:20.702047431Z [Info] ReleaseSearchService: Searching indexer(s): [1337x] for Term: [] for Season / Episode:[], Offset: 0, Limit: 100, Categories: [5000, 5040, 5030, 5070] 
2024-07-16T06:13:31.158902892Z [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
2024-07-16T06:13:31.158929882Z  -- : Unable to access www.ygg.re, blocked by CloudFlare Protection. 
2024-07-16T06:14:41.708164772Z [Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [POST] http://192.168.0.17:8191/v1: 500.InternalServerError (182 bytes)
2024-07-16T06:14:41.708211538Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110420917 endTimestamp=1721110481703 version=3.3.21
2024-07-16T06:14:41.720211420Z [Warn] Cardigann: Request for YGGcookie failed with exception 'HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]'. Retrying in 2.7038557s. 
2024-07-16T06:14:41.720256842Z 
2024-07-16T06:14:41.720270428Z [v1.20.1.4603] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]
2024-07-16T06:14:41.720282739Z    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
2024-07-16T06:14:41.720294750Z    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
2024-07-16T06:14:41.720306567Z    at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 57
2024-07-16T06:14:41.720343389Z    at NzbDrone.Core.Indexers.IndexerHttpClient.<>c.<PostResponse>b__6_0(HttpResponse current, IIndexerProxy selectedProxy) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:14:41.720355233Z    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
2024-07-16T06:14:41.720364091Z    at NzbDrone.Core.Indexers.IndexerHttpClient.PostResponse(HttpResponse response, IList`1 selectedProxies) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:14:41.720373307Z    at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 44
2024-07-16T06:14:41.720382781Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.<>c.<<FetchIndexerResponse>b__57_0>d.MoveNext() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 664
2024-07-16T06:14:41.720393001Z --- End of stack trace from previous location ---
2024-07-16T06:14:41.720401773Z    at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
2024-07-16T06:14:41.720411830Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110420917 endTimestamp=1721110481703 version=3.3.21
2024-07-16T06:14:41.720423262Z 
2024-07-16T06:14:41.720431438Z 
2024-07-16T06:15:45.201232960Z [Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [POST] http://192.168.0.17:8191/v1: 500.InternalServerError (182 bytes)
2024-07-16T06:15:45.201264270Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110484482 endTimestamp=1721110545198 version=3.3.21
2024-07-16T06:15:45.203476642Z [Warn] Cardigann: Request for YGGcookie failed with exception 'HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]'. Retrying in 2.4590055s. 
2024-07-16T06:15:45.203496961Z 
2024-07-16T06:15:45.203502535Z [v1.20.1.4603] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]
2024-07-16T06:15:45.203507503Z    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
2024-07-16T06:15:45.203512045Z    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
2024-07-16T06:15:45.203516665Z    at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 57
2024-07-16T06:15:45.203521560Z    at NzbDrone.Core.Indexers.IndexerHttpClient.<>c.<PostResponse>b__6_0(HttpResponse current, IIndexerProxy selectedProxy) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:15:45.203527026Z    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
2024-07-16T06:15:45.203531819Z    at NzbDrone.Core.Indexers.IndexerHttpClient.PostResponse(HttpResponse response, IList`1 selectedProxies) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:15:45.203547474Z    at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 44
2024-07-16T06:15:45.203552180Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.<>c.<<FetchIndexerResponse>b__57_0>d.MoveNext() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 664
2024-07-16T06:15:45.203556555Z --- End of stack trace from previous location ---
2024-07-16T06:15:45.203559842Z    at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
2024-07-16T06:15:45.203563586Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110484482 endTimestamp=1721110545198 version=3.3.21
2024-07-16T06:15:45.203568264Z 
2024-07-16T06:15:45.203571325Z 
2024-07-16T06:16:48.494876876Z [Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [POST] http://192.168.0.17:8191/v1: 500.InternalServerError (182 bytes)
2024-07-16T06:16:48.494914538Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110547808 endTimestamp=1721110608493 version=3.3.21
2024-07-16T06:16:48.498291452Z [Warn] Cardigann: Unable to connect to indexer 
2024-07-16T06:16:48.498311802Z 
2024-07-16T06:16:48.498317235Z [v1.20.1.4603] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]
2024-07-16T06:16:48.498322012Z    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
2024-07-16T06:16:48.498326168Z    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
2024-07-16T06:16:48.498330084Z    at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 57
2024-07-16T06:16:48.498333901Z    at NzbDrone.Core.Indexers.IndexerHttpClient.<>c.<PostResponse>b__6_0(HttpResponse current, IIndexerProxy selectedProxy) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:16:48.498338357Z    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
2024-07-16T06:16:48.498342204Z    at NzbDrone.Core.Indexers.IndexerHttpClient.PostResponse(HttpResponse response, IList`1 selectedProxies) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:16:48.498345856Z    at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 44
2024-07-16T06:16:48.498349441Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.<>c.<<FetchIndexerResponse>b__57_0>d.MoveNext() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 664
2024-07-16T06:16:48.498353363Z --- End of stack trace from previous location ---
2024-07-16T06:16:48.498357241Z    at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
2024-07-16T06:16:48.498370217Z --- End of stack trace from previous location ---
2024-07-16T06:16:48.498373475Z    at Polly.Outcome`1.GetResultOrRethrow()
2024-07-16T06:16:48.498376719Z    at Polly.ResiliencePipeline.ExecuteAsync[TResult,TState](Func`3 callback, TState state, CancellationToken cancellationToken)
2024-07-16T06:16:48.498379612Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 663
2024-07-16T06:16:48.498382628Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 581
2024-07-16T06:16:48.498386834Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 763
2024-07-16T06:16:48.498390007Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110547808 endTimestamp=1721110608493 version=3.3.21
2024-07-16T06:16:48.498394298Z 
2024-07-16T06:16:48.498396905Z 
2024-07-16T06:16:48.520682543Z [Warn] ProwlarrErrorPipeline: Invalid request Validation failed: 
2024-07-16T06:16:48.520699966Z  -- : Unable to connect to indexer, indexer's server is unavailable. Try again later. HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1] 
2024-07-16T06:21:06.097264372Z [Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [POST] http://192.168.0.17:8191/v1: 500.InternalServerError (182 bytes)
2024-07-16T06:21:06.097295427Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110805425 endTimestamp=1721110866094 version=3.3.21
2024-07-16T06:21:06.099804830Z [Warn] Cardigann: Request for YGGtorrent failed with exception 'HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]'. Retrying in 0.9783614s. 
2024-07-16T06:21:06.099827233Z 
2024-07-16T06:21:06.099833102Z [v1.20.1.4603] NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.0.17:8191/v1]
2024-07-16T06:21:06.099838405Z    at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 128
2024-07-16T06:21:06.099843326Z    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Prowlarr.Common/Http/HttpClient.cs:line 137
2024-07-16T06:21:06.099848357Z    at NzbDrone.Core.IndexerProxies.FlareSolverr.FlareSolverr.PostResponse(HttpResponse response) in ./Prowlarr.Core/IndexerProxies/FlareSolverr/FlareSolverr.cs:line 57
2024-07-16T06:21:06.099853788Z    at NzbDrone.Core.Indexers.IndexerHttpClient.<>c.<PostResponse>b__6_0(HttpResponse current, IIndexerProxy selectedProxy) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:21:06.099859476Z    at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
2024-07-16T06:21:06.099864194Z    at NzbDrone.Core.Indexers.IndexerHttpClient.PostResponse(HttpResponse response, IList`1 selectedProxies) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 95
2024-07-16T06:21:06.099880643Z    at NzbDrone.Core.Indexers.IndexerHttpClient.ExecuteProxiedAsync(HttpRequest request, ProviderDefinition definition) in ./Prowlarr.Core/Indexers/IndexerHttpClient.cs:line 44
2024-07-16T06:21:06.099885222Z    at NzbDrone.Core.Indexers.HttpIndexerBase`1.<>c.<<FetchIndexerResponse>b__57_0>d.MoveNext() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 664
2024-07-16T06:21:06.099899320Z --- End of stack trace from previous location ---
2024-07-16T06:21:06.099903292Z    at Polly.ResiliencePipeline.<>c__9`2.<<ExecuteAsync>b__9_0>d.MoveNext()
2024-07-16T06:21:06.099907442Z Error: Error solving the challenge. Timeout after 60.0 seconds. | status=error startTimestamp=1721110805425 endTimestamp=1721110866094 version=3.3.21
2024-07-16T06:21:06.099912277Z 
2024-07-16T06:21:06.099915455Z 
```

**Flaresolverr**
```
2024-07-16 05:11:55 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 05:11:56 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 05:11:56 INFO     Response in 60.749 s
2024-07-16 05:11:56 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 05:11:58 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 05:11:59 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 05:12:55 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 05:12:55 INFO     Response in 60.8 s
2024-07-16 05:12:55 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 05:12:58 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 05:12:58 INFO     Response in 60.82 s
2024-07-16 05:12:58 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:01:22 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:01:23 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:02:22 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:02:22 INFO     Response in 60.687 s
2024-07-16 06:02:22 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:02:24 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:02:25 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:02:52 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:02:53 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:03:25 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:03:25 INFO     Response in 60.786 s
2024-07-16 06:03:25 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:03:26 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:03:27 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:03:53 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:03:53 INFO     Response in 60.793 s
2024-07-16 06:03:53 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:03:54 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:03:55 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:04:27 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:04:27 INFO     Response in 60.658 s
2024-07-16 06:04:27 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:04:55 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:04:55 INFO     Response in 60.687 s
2024-07-16 06:04:55 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:04:59 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:05:00 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:06:00 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:06:00 INFO     Response in 60.658 s
2024-07-16 06:06:00 INFO     172.17.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:07:50 INFO     FlareSolverr 3.3.21
2024-07-16 06:07:50 INFO     Testing web browser installation...
2024-07-16 06:07:50 INFO     Platform: Linux-6.8.0-38-generic-x86_64-with-glibc2.31
2024-07-16 06:07:50 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-07-16 06:07:50 INFO     Chrome / Chromium major version: 120
2024-07-16 06:07:50 INFO     Launching web browser...
2024-07-16 06:07:51 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-07-16 06:07:51 INFO     Test successful!
2024-07-16 06:07:51 INFO     Serving on http://0.0.0.0:8191
2024-07-16 06:08:11 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
2024-07-16 06:08:12 INFO     Challenge not detected!
2024-07-16 06:08:12 INFO     Response in 1.203 s
2024-07-16 06:08:12 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 200 OK
2024-07-16 06:08:18 INFO     192.168.0.16 GET http://192.168.0.17:8191/ 200 OK
2024-07-16 06:09:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://prowlarr.servarr.com/v1/ping', 'proxy': {}}
2024-07-16 06:09:41 INFO     Challenge not detected!
2024-07-16 06:09:41 INFO     Response in 1.174 s
2024-07-16 06:09:41 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 200 OK
2024-07-16 06:13:20 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://1337x.to/cat/Movies/time/desc/1/', 'proxy': {}}
2024-07-16 06:13:22 INFO     Challenge not detected!
2024-07-16 06:13:23 INFO     Response in 2.349 s
2024-07-16 06:13:23 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 200 OK
2024-07-16 06:13:40 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:13:41 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:14:41 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:14:41 INFO     Response in 60.786 s
2024-07-16 06:14:41 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:14:44 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:14:45 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:15:45 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:15:45 INFO     Response in 60.716 s
2024-07-16 06:15:45 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:15:47 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:15:48 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:16:48 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:16:48 INFO     Response in 60.685 s
2024-07-16 06:16:48 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:19:10 INFO     FlareSolverr 3.3.21
2024-07-16 06:19:10 INFO     Testing web browser installation...
2024-07-16 06:19:10 INFO     Platform: Linux-6.8.0-38-generic-x86_64-with-glibc2.31
2024-07-16 06:19:10 INFO     Chrome / Chromium path: /usr/bin/chromium
2024-07-16 06:19:10 INFO     Chrome / Chromium major version: 120
2024-07-16 06:19:10 INFO     Launching web browser...
2024-07-16 06:19:11 INFO     FlareSolverr User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
2024-07-16 06:19:11 INFO     Test successful!
2024-07-16 06:19:11 INFO     Serving on http://0.0.0.0:8191
2024-07-16 06:20:05 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:20:06 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:21:06 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:21:06 INFO     Response in 60.669 s
2024-07-16 06:21:06 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:21:07 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:21:08 INFO     Challenge detected. Title found: Just a moment...
2024-07-16 06:22:07 ERROR    Error: Error solving the challenge. Timeout after 60.0 seconds.
2024-07-16 06:22:07 INFO     Response in 60.69 s
2024-07-16 06:22:07 INFO     172.18.0.1 POST http://192.168.0.17:8191/v1 500 Internal Server Error
2024-07-16 06:22:10 INFO     Incoming request => POST /v1 body: {'maxTimeout': 60000, 'cmd': 'request.get', 'url': 'https://www.ygg.re/engine/search?category=all&do=search&order=desc&sort=publish_date', 'proxy': {}}
2024-07-16 06:22:11 INFO     Challenge detected. Title found: Just a moment...
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Please use [Discord](https://prowlarr.com/discord) for support/questions.
