### ISSUE TITLE
OxTorrent new URL

### ISSUE THREAD

**Issue by hvmzx** [Prowlarr/Indexers#487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

OxTorrent-vip's new url is https://www.oxtorrent.gy (that url is shown when visiting the current url)
Also, OxTorrent (nonVIP) is an unofficial copy with missing stuff (as it's late compared to the original) so it should be deleted (and remove vip from OxTorrent title as there is no such thing as vip).

Official website showing the previous domains, the current one, the fake ones : https://www.oxtorrent.info/

### Expected Behavior

OxTorrent to redirect to https://www.oxtorrent.gy

### Environment

```markdown
- OS: Ubuntu latest
- Prowlarr: 1.24.3.4754
- Docker Install: yes
- Using Reverse Proxy: no
- Browser:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**
```
2024-10-05 23:41:01.6|Debug|Prowlarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2024-10-05 23:41:01.6|Trace|Cardigann|Getting Basic search
2024-10-05 23:41:01.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-10-05 23:41:01.6|Trace|Cardigann|Populating config vars
2024-10-05 23:41:01.6|Debug|Cardigann|Adding request for OxTorrent-vip: https://www.oxtorrent.gl/derniers
2024-10-05 23:41:01.6|Debug|Cardigann|Downloading Feed https://www.oxtorrent.gl/derniers
2024-10-05 23:41:01.6|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-10-05 23:41:01.6|Trace|IndexerHttpClient|Req: [GET] https://www.oxtorrent.gl/derniers
2024-10-05 23:41:01.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2024-10-05 23:41:01.7|Trace|IndexerHttpClient|Res: HTTP/2.0 [GET] https://www.oxtorrent.gl/derniers: 301.Moved (296 bytes) (41 ms)
2024-10-05 23:41:01.7|Debug|FlareSolverr|CF Protection not detected, returning original response
2024-10-05 23:41:01.7|Trace|Cardigann|Cardigann (oxtorrent-vip): Parsing response
2024-10-05 23:41:01.7|Trace|ConfigService|Using default config value for 'logindexerresponse' defaultValue:'False'
2024-10-05 23:41:01.7|Warn|Cardigann|Redirected to https://oxtorrent.blog/ from indexer request
2024-10-05 23:41:01.7|Trace|Cardigann|Unexpected Response content (296 bytes): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://oxtorrent.blog">here</a>.</p>
<hr>
<address>Apache Server at www.oxtorrent.gl Port 80</address>
</body></html>

2024-10-05 23:41:01.7|Warn|Cardigann|Unable to connect to indexer

[v1.24.3.4754] NzbDrone.Core.Indexers.Exceptions.IndexerException: Redirected to https://oxtorrent.blog/ from indexer request
   at NzbDrone.Core.Indexers.Definitions.Cardigann.CardigannParser.ParseResponse(IndexerResponse indexerResponse) in ./Prowlarr.Core/Indexers/Definitions/Cardigann/CardigannParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 606
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in ./Prowlarr.Core/Indexers/HttpIndexerBase.cs:line 760
RequestUri: https://www.oxtorrent.gl/derniers;StatusCode: Moved;ContentType: text/html; charset=iso-8859-1;ContentLength: 296;ContentSample: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://oxtorrent.blog">here</a>.</p>
<hr>
<address>Apache Server at www.oxtorrent.gl Port 80</address>
</body></html>```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
This is already done? https://github.com/Prowlarr/Indexers/blob/18f123101ecc1a24f53f678ed7605f7c03f3cddf/definitions/v10/oxtorrent-vip.yml#L13

**Comment by hvmzx** [comment]
> This is already done?
> 
> https://github.com/Prowlarr/Indexers/blob/18f123101ecc1a24f53f678ed7605f7c03f3cddf/definitions/v10/oxtorrent-vip.yml#L13

This is the old url, new url ends with .gy. 

- Change the url from .gl to .gy
- Remove OxTorrent
- Rename OxTorrent-vip to OxTorrent (as there is no such thing as vip, and the current OxTorrent is an unofficial copy)
